login:
    path: /auth/login
    controller: App\Controller\AuthController::login

logout:
    path: /auth/logout
    controller: App\Controller\AuthController::logout

register:
    path: /auth/register
    controller: App\Controller\AuthController::register

check_credentials:
    path: /auth/check-credentials
    methods: POST
    controller: App\Controller\AuthController::checkCredentials
