login:
    path: /auth/login
    controller: App\Controller\AuthController::login

logout:
    path: /auth/logout
    controller: App\Controller\AuthController::logout

register:
    path: /auth/register
    controller: App\Controller\AuthController::register
